---
- name: Configure Nomad Client
  hosts: all
  become: yes
  gather_facts: true

  vars:
    nomad:
      version: '0.8.1'

  tasks:
  - name: APT Install Required Packages
    apt:
      pkg: "{{ item }}"
      force: yes
      update_cache: yes
      state: present
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

  - name: Add Docker GPG key
    apt_key:
      id: "58118E89F3A912897C070ADBF76221572C52609D"
      keyserver: "hkp://p80.pool.sks-keyservers.net:80"
      state: present

  - name: Add Docker APT Repository
    apt_repository:
      repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable'
      state: present

  - name: APT Install Docker CE
    apt:
      pkg: docker-ce
      force: yes
      update_cache: yes
      state: present

  - name: Copy nomad configuration
    template:
      src: nomad_client.config
      dest: /opt/nomad/config/nomad_client_config.json

  - name: Install service file
    copy:
      src: nomad_client.service
      dest: /etc/systemd/system/nomad_client.service

  - name: Start nomad
    service:
      name: nomad_client
      state: started
