################################################################
# Global configuration
################################################################
defaultEntryPoints = ["http"]

################################################################
# Entrypoints configuration
################################################################
[entryPoints]
    [entryPoints.http]
    address = ":8081"

################################################################
# API and dashboard configuration
################################################################
[api]

################################################################
# Ping configuration
################################################################
[ping]

################################################################
# Consul Catalog configuration backend
################################################################
[consulCatalog]

endpoint = "127.0.0.1:8500"
exposedByDefault = false
prefix = "traefik"
domain = "test.localhost"
frontEndRule = "Host:{{.ServiceName}}.{{.Domain}}"
